# Generated by Django 2.2.4 on 2020-03-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time this model was created at.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The last time this model was modified at.')),
                ('name', models.CharField(editable=False, help_text='The name provided by the user.', max_length=100)),
                ('email', models.EmailField(editable=False, help_text='The email provided by the user.', max_length=254)),
                ('message', models.TextField(editable=False, help_text='The message provided by the user.', max_length=2047)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='An image representing the project', upload_to='')),
                ('name', models.CharField(help_text='The name or title of the project.', max_length=100)),
                ('description', models.TextField(help_text='A description of the project.', max_length=2047)),
                ('local_link', models.URLField(blank=True, help_text='Link to the running project.')),
                ('source_link', models.URLField(blank=True, help_text="Link to the project's source code.")),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
